#!/usr/bin/python3
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
"""

def fib(n):
    lis = []
    res = 0 
    pre = 1
    pos = 0
    i = 1
    while i <= n:
        res =  pre + pos
        pre = pos
        pos = res
        i += 1
        lis.append(res)
   # print(lis)
    return res

j = 1
while fib(j) <= 4000000:
     j += 1
     print("Fib {} is {}".format(j-1, fib(j)))
print(j)
